In [1]:
import utils
import psycopg2
import pandas as pd
import numpy as np

In [100]:
conn = psycopg2.connect(dbname='league', user=utils.pgUsername, password=utils.pgPassword)
cursor = conn.cursor()
cursor.execute("SELECT * FROM games WHERE gameversion LIKE '10.20%'")
records = cursor.fetchall()

In [107]:
description = cursor.description
cols = [c.name for c in description]
df = pd.DataFrame(records)
df.columns = cols

In [102]:
utils.write_list(records,'test_records.txt')

In [112]:
def getDescriptives(df,column):
    c = list()
    for p in range(10):
        c.append(f"p{p+1}_{column}")
    df[f"sum_{column}"]  = df[c].sum(axis=1)
    df[f"mean_{column}"] = df[c].mean(axis=1)
    df[f"std_{column}"]  = df[c].std(axis=1)
    
    players = [[1,2,3,4,5],[6,7,8,9,10]]
    teams = ['blue','red']
    for idx, team in enumerate(teams):
        d = list()
        for p in players[idx]:
            d.append(f"p{p}_{column}")
        
        df[f"sum_{team}_{column}"]  = df[d].sum(axis=1)
        df[f"mean_{team}_{column}"] = df[d].mean(axis=1)
        df[f"std_{team}_{column}"]  = df[d].std(axis=1)
    
    for p in range(10):
        df[f"p{p+1}_z_{column}"] = (df[c[p]]-df[f"mean_{column}"])/df[f"std_{column}"]

In [113]:
getDescriptives(df,'totaldamagedealttochampions')
getDescriptives(df,'damagedealttoobjectives')

In [118]:
damageCols = [key for key in df.columns if 'totaldamagedealttochampions' in key]
df[damageCols]

,p1_totaldamagedealttochampions,p2_totaldamagedealttochampions,p3_totaldamagedealttochampions,p4_totaldamagedealttochampions,p5_totaldamagedealttochampions,p6_totaldamagedealttochampions,p7_totaldamagedealttochampions,p8_totaldamagedealttochampions,p9_totaldamagedealttochampions,p10_totaldamagedealttochampions,...,p1_z_totaldamagedealttochampions,p2_z_totaldamagedealttochampions,p3_z_totaldamagedealttochampions,p4_z_totaldamagedealttochampions,p5_z_totaldamagedealttochampions,p6_z_totaldamagedealttochampions,p7_z_totaldamagedealttochampions,p8_z_totaldamagedealttochampions,p9_z_totaldamagedealttochampions,p10_z_totaldamagedealttochampions
0,17595.0,10358.0,13130.0,8239.0,9159.0,6970.0,18415.0,14628.0,7051.0,8891.0,...,1.450276,-0.255945,0.397592,-0.755528,-0.538626,-1.054712,1.643603,0.750766,-1.035615,-0.601810
1,22799.0,5398.0,27853.0,32802.0,18906.0,18821.0,10709.0,34231.0,29195.0,24943.0,...,0.025041,-1.842693,0.567512,1.098712,-0.392813,-0.401937,-1.272637,1.252093,0.711555,0.255167
2,16071.0,9352.0,29382.0,43634.0,18579.0,18673.0,19452.0,12754.0,33374.0,13881.0,...,-0.510061,-1.139556,0.737031,2.072285,-0.275089,-0.266282,-0.193299,-0.820827,1.111037,-0.715239
3,6216.0,20688.0,8753.0,8217.0,9269.0,24608.0,19939.0,7887.0,8649.0,20559.0,...,-1.035412,1.027856,-0.673713,-0.750130,-0.600147,1.586728,0.921071,-0.797178,-0.688540,1.009464
4,16519.0,7719.0,15632.0,19562.0,9879.0,15804.0,12401.0,13905.0,11564.0,9386.0,...,0.885594,-1.489015,0.646245,1.706724,-0.906156,0.692657,-0.225615,0.180227,-0.451473,-1.039189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21785,13798.0,23922.0,7334.0,18999.0,10914.0,6902.0,16613.0,20864.0,12303.0,14278.0,...,-0.142172,1.669013,-1.298582,0.788288,-0.658120,-1.375867,0.361432,1.121936,-0.409628,-0.056300
21786,12626.0,19091.0,18262.0,26806.0,15132.0,12280.0,14273.0,26328.0,26082.0,18241.0,...,-1.109442,0.031574,-0.114737,1.393205,-0.667155,-1.170508,-0.818761,1.308842,1.265426,-0.118443
21787,5705.0,17870.0,8415.0,17211.0,5258.0,17707.0,6135.0,4404.0,13112.0,11727.0,...,-0.921876,1.299105,-0.427107,1.178790,-1.003485,1.269346,-0.843370,-1.159401,0.430430,0.177569
21788,11614.0,19317.0,20182.0,11393.0,7379.0,14372.0,15928.0,8133.0,28455.0,21588.0,...,-0.638197,0.526160,0.656910,-0.671602,-1.278343,-0.221308,0.013891,-1.164371,1.907425,0.869435
21789,17733.0,8784.0,28260.0,20249.0,30119.0,17860.0,10189.0,14471.0,27167.0,8249.0,...,-0.070799,-1.172480,1.225145,0.238938,1.454001,-0.055164,-0.999515,-0.472373,1.090590,-1.238342

In [121]:
damageCols = [key for key in df.columns if 'damage' in key]
display(damageCols)

['p1_totaldamagedealttochampions',
 'p1_magicdamagedealttochampions',
 'p1_physicaldamagedealttochampions',
 'p1_truedamagedealttochampions',
 'p1_damageselfmitigated',
 'p1_damagedealttoobjectives',
 'p1_damagedealttoturrets',
 'p1_totaldamagetaken',
 'p1_magicaldamagetaken',
 'p1_physicaldamagetaken',
 'p1_truedamagetaken',
 'p2_totaldamagedealttochampions',
 'p2_magicdamagedealttochampions',
 'p2_physicaldamagedealttochampions',
 'p2_truedamagedealttochampions',
 'p2_damageselfmitigated',
 'p2_damagedealttoobjectives',
 'p2_damagedealttoturrets',
 'p2_totaldamagetaken',
 'p2_magicaldamagetaken',
 'p2_physicaldamagetaken',
 'p2_truedamagetaken',
 'p3_totaldamagedealttochampions',
 'p3_magicdamagedealttochampions',
 'p3_physicaldamagedealttochampions',
 'p3_truedamagedealttochampions',
 'p3_damageselfmitigated',
 'p3_damagedealttoobjectives',
 'p3_damagedealttoturrets',
 'p3_totaldamagetaken',
 'p3_magicaldamagetaken',
 'p3_physicaldamagetaken',
 'p3_truedamagetaken',
 'p4_totaldamagedealttochampions',
 'p4_magicdamagedealttochampions',
 'p4_physicaldamagedealttochampions',
 'p4_truedamagedealttochampions',
 'p4_damageselfmitigated',
 'p4_damagedealttoobjectives',
 'p4_damagedealttoturrets',
 'p4_totaldamagetaken',
 'p4_magicaldamagetaken',
 'p4_physicaldamagetaken',
 'p4_truedamagetaken',
 'p5_totaldamagedealttochampions',
 'p5_magicdamagedealttochampions',
 'p5_physicaldamagedealttochampions',
 'p5_truedamagedealttochampions',
 'p5_damageselfmitigated',
 'p5_damagedealttoobjectives',
 'p5_damagedealttoturrets',
 'p5_totaldamagetaken',
 'p5_magicaldamagetaken',
 'p5_physicaldamagetaken',
 'p5_truedamagetaken',
 'p6_totaldamagedealttochampions',
 'p6_magicdamagedealttochampions',
 'p6_physicaldamagedealttochampions',
 'p6_truedamagedealttochampions',
 'p6_damageselfmitigated',
 'p6_damagedealttoobjectives',
 'p6_damagedealttoturrets',
 'p6_totaldamagetaken',
 'p6_magicaldamagetaken',
 'p6_physicaldamagetaken',
 'p6_truedamagetaken',
 'p7_totaldamagedealttochampions',
 'p7_magicdamagedealttochampions',
 'p7_physicaldamagedealttochampions',
 'p7_truedamagedealttochampions',
 'p7_damageselfmitigated',
 'p7_damagedealttoobjectives',
 'p7_damagedealttoturrets',
 'p7_totaldamagetaken',
 'p7_magicaldamagetaken',
 'p7_physicaldamagetaken',
 'p7_truedamagetaken',
 'p8_totaldamagedealttochampions',
 'p8_magicdamagedealttochampions',
 'p8_physicaldamagedealttochampions',
 'p8_truedamagedealttochampions',
 'p8_damageselfmitigated',
 'p8_damagedealttoobjectives',
 'p8_damagedealttoturrets',
 'p8_totaldamagetaken',
 'p8_magicaldamagetaken',
 'p8_physicaldamagetaken',
 'p8_truedamagetaken',
 'p9_totaldamagedealttochampions',
 'p9_magicdamagedealttochampions',
 'p9_physicaldamagedealttochampions',
 'p9_truedamagedealttochampions',
 'p9_damageselfmitigated',
 'p9_damagedealttoobjectives',
 'p9_damagedealttoturrets',
 'p9_totaldamagetaken',
 'p9_magicaldamagetaken',
 'p9_physicaldamagetaken',
 'p9_truedamagetaken',
 'p10_totaldamagedealttochampions',
 'p10_magicdamagedealttochampions',
 'p10_physicaldamagedealttochampions',
 'p10_truedamagedealttochampions',
 'p10_damageselfmitigated',
 'p10_damagedealttoobjectives',
 'p10_damagedealttoturrets',
 'p10_totaldamagetaken',
 'p10_magicaldamagetaken',
 'p10_physicaldamagetaken',
 'p10_truedamagetaken',
 'sum_totaldamagedealttochampions',
 'mean_totaldamagedealttochampions',
 'std_totaldamagedealttochampions',
 'sum_blue_totaldamagedealttochampions',
 'mean_blue_totaldamagedealttochampions',
 'std_blue_totaldamagedealttochampions',
 'sum_red_totaldamagedealttochampions',
 'mean_red_totaldamagedealttochampions',
 'std_red_totaldamagedealttochampions',
 'p1_z_totaldamagedealttochampions',
 'p2_z_totaldamagedealttochampions',
 'p3_z_totaldamagedealttochampions',
 'p4_z_totaldamagedealttochampions',
 'p5_z_totaldamagedealttochampions',
 'p6_z_totaldamagedealttochampions',
 'p7_z_totaldamagedealttochampions',
 'p8_z_totaldamagedealttochampions',
 'p9_z_totaldamagedealttochampions',
 'p10_z_totaldamagedealttochampions',
 'sum_damagedealttoobjectives',
 'mean_damagedealttoobjectives',
 'std_damagedealttoobjectives',
 'sum_blue_damagedealttoobjectives',
 'mean_blue_damagedealttoobjectives',
 'std_blue_damagedealttoobjectives',
 'sum_red_damagedealttoobjectives',
 'mean_red_damagedealttoobjectives',
 'std_red_damagedealttoobjectives',
 'p1_z_damagedealttoobjectives',
 'p2_z_damagedealttoobjectives',
 'p3_z_damagedealttoobjectives',
 'p4_z_damagedealttoobjectives',
 'p5_z_damagedealttoobjectives',
 'p6_z_damagedealttoobjectives',
 'p7_z_damagedealttoobjectives',
 'p8_z_damagedealttoobjectives',
 'p9_z_damagedealttoobjectives',
 'p10_z_damagedealttoobjectives']

In [80]:
display(df[['p1_totaldamagedealttochampions','mean_totaldamagedealttochampions','std_totaldamagedealttochampions','p1_z_totaldamagedealttochampions']])

,p1_totaldamagedealttochampions,mean_totaldamagedealttochampions,std_totaldamagedealttochampions,p1_z_totaldamagedealttochampions
0,13921.0,11052.4,3668.879672,0.781874
1,29285.0,22762.8,7886.628414,0.826995
2,17605.0,20356.2,9533.541301,-0.288581
3,17000.0,15784.7,7931.426718,0.153226
4,20732.0,15396.9,4662.135192,1.144347
...,...,...,...,...
14367,5717.0,8844.2,3877.519820,-0.806495
14368,21874.0,29406.4,11433.268311,-0.658814
14369,16828.0,11956.9,4639.431418,1.049935
14370,22348.0,22274.8,11978.450176,0.006111
14371,5460.0,7649.7,3288.686062,-0.665828

In [106]:
df['p1_teamid']

0        None
1        None
2        None
3        None
4        None
         ...
21785    None
21786    None
21787    None
21788    None
21789    None
Name: p1_teamid, Length: 21790, dtype: object

In [88]:
data = dict()
for p in range(10):
    for lane in ['TOP','MIDDLE','JUNGLE','BOTTOM']:    
        if lane='BOTTOM':           
            
        else:
            df[lane] = df[df[]]
        
        'DUO_CARRY'
        'DUO_SUPPORT'
a = df['p1_lane']=="BOTTOM"
b = df['p1_role']=="DUO_CARRY"

#df[['p1_role','p1_lane']][]

In [95]:
a = pd.DataFrame()
a[['one','two']] = df[['p1_lane','p1_role']][df['p1_lane']=='BOTTOM']

In [96]:
display(a)

          one          two
4      BOTTOM    DUO_CARRY
5      BOTTOM    DUO_CARRY
7      BOTTOM  DUO_SUPPORT
8      BOTTOM    DUO_CARRY
9      BOTTOM    DUO_CARRY
...       ...          ...
14362  BOTTOM    DUO_CARRY
14363  BOTTOM    DUO_CARRY
14365  BOTTOM    DUO_CARRY
14366  BOTTOM  DUO_SUPPORT
14368  BOTTOM    DUO_CARRY

[4481 rows x 2 columns]

In [97]:
b = a.append(a)

In [98]:
display(b)

          one          two
4      BOTTOM    DUO_CARRY
5      BOTTOM    DUO_CARRY
7      BOTTOM  DUO_SUPPORT
8      BOTTOM    DUO_CARRY
9      BOTTOM    DUO_CARRY
...       ...          ...
14362  BOTTOM    DUO_CARRY
14363  BOTTOM    DUO_CARRY
14365  BOTTOM    DUO_CARRY
14366  BOTTOM  DUO_SUPPORT
14368  BOTTOM    DUO_CARRY

[8962 rows x 2 columns]